name: GOTRAVEL
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run generator
        run: ./gotravel_linux_arm64
        
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GOTRAVEL_TOKEN }}
          branch: master
